# build with: docker buildx build --platform linux/amd64,linux/arm64 -t my-n8n:bookworm --push .

FROM debian:bookworm-slim
ARG TARGETARCH
ENV DEBIAN_FRONTEND=noninteractive

# Common deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates gnupg python3 wget xz-utils \
    ffmpeg imagemagick ghostscript fontconfig \
    && rm -rf /var/lib/apt/lists/*

# Node 20 (works on amd64 & arm64)
RUN mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
    | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x bookworm main" \
    > /etc/apt/sources.list.d/nodesource.list \
 && apt-get update && apt-get install -y --no-install-recommends nodejs \
 && rm -rf /var/lib/apt/lists/*

# n8n
RUN npm i -g --omit=dev n8n

# Calibre:
# - On amd64: install latest via upstream installer
# - On arm64: install Debian package (works on ARM, but might be older)
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      wget -nv -O- https://download.calibre-ebook.com/linux-installer.py \
      | python3 -c "import sys; exec(sys.stdin.read())"; \
    else \
      apt-get update && apt-get install -y --no-install-recommends calibre && \
      rm -rf /var/lib/apt/lists/*; \
    fi

ENV PATH="/opt/calibre:${PATH}"

# Non-root user
RUN useradd -m -u 1000 -s /bin/bash node \
 && mkdir -p /home/node/.n8n /data \
 && chown -R node:node /home/node /data
USER node
ENV N8N_USER_FOLDER=/home/node/.n8n
WORKDIR /home/node

EXPOSE 5678
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=5 \
  CMD curl -fsS http://localhost:5678/healthz || exit 1
CMD ["n8n"]
